package cn.mogeek.rmi.ptteng.model;

import lombok.Data;

import java.io.Serializable;
import java.util.Date;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table direction
 *
 * @mbg.generated do_not_delete_during_merge Mon Jul 20 02:59:46 CST 2020
 */
@Data
public class Direction implements Serializable {
    private static final long serialVersionUID = -8199494440875896491L;
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column direction.id
     *
     * @mbg.generated Mon Jul 20 02:59:46 CST 2020
     */
    private Integer id;

    /**
     * Database Column Remarks:
     *   职业方向
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column direction.career_direction
     *
     * @mbg.generated Mon Jul 20 02:59:46 CST 2020
     */
    private String careerDirection;

    /**
     * Database Column Remarks:
     *   累计学习人数
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column direction.number_of_student
     *
     * @mbg.generated Mon Jul 20 02:59:46 CST 2020
     */
    private Integer numberOfStudent;

    /**
     * Database Column Remarks:
     *   就业人数
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column direction.employed_population
     *
     * @mbg.generated Mon Jul 20 02:59:46 CST 2020
     */
    private Integer employedPopulation;

    /**
     * Database Column Remarks:
     *   更新时间
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column direction.updateat
     *
     * @mbg.generated Mon Jul 20 02:59:46 CST 2020
     */
    private Date updateat;

    /**
     * Database Column Remarks:
     *   创建时间
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column direction.createat
     *
     * @mbg.generated Mon Jul 20 02:59:46 CST 2020
     */
    private Date createat;
}