package cn.mogeek.rmi.ptteng.model;

import lombok.Data;

import java.io.Serializable;
import java.util.Date;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table login_user
 *
 * @mbg.generated do_not_delete_during_merge Mon Jul 20 02:59:46 CST 2020
 */
@Data
public class LoginUser implements Serializable {
    private static final long serialVersionUID = -7249659724871327052L;
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column login_user.id
     *
     * @mbg.generated Mon Jul 20 02:59:46 CST 2020
     */
    private Integer id;

    /**
     * Database Column Remarks:
     *   用户名
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column login_user.name
     *
     * @mbg.generated Mon Jul 20 02:59:46 CST 2020
     */
    private String name;

    /**
     * Database Column Remarks:
     *   用户头像
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column login_user.head
     *
     * @mbg.generated Mon Jul 20 02:59:46 CST 2020
     */
    private String head;

    /**
     * Database Column Remarks:
     *   密码加密值
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column login_user.passwd
     *
     * @mbg.generated Mon Jul 20 02:59:46 CST 2020
     */
    private String passwd;

    /**
     * Database Column Remarks:
     *   邮箱
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column login_user.email
     *
     * @mbg.generated Mon Jul 20 02:59:46 CST 2020
     */
    private String email;

    /**
     * Database Column Remarks:
     *   手机号码
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column login_user.phone_number
     *
     * @mbg.generated Mon Jul 20 02:59:46 CST 2020
     */
    private String phoneNumber;

    /**
     * Database Column Remarks:
     *   更新时间
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column login_user.updateat
     *
     * @mbg.generated Mon Jul 20 02:59:46 CST 2020
     */
    private Date updateat;

    /**
     * Database Column Remarks:
     *   创建时间
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column login_user.createat
     *
     * @mbg.generated Mon Jul 20 02:59:46 CST 2020
     */
    private Date createat;
}