package cn.mogeek.rmi.ptteng.model;

import lombok.Data;

import java.io.Serializable;
import java.util.Date;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table occupation
 *
 * @mbg.generated do_not_delete_during_merge Mon Jul 20 02:59:46 CST 2020
 */
@Data
public class Occupation implements Serializable {
    private static final long serialVersionUID = 473323553210521802L;
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column occupation.id
     *
     * @mbg.generated Mon Jul 20 02:59:46 CST 2020
     */
    private Integer id;

    /**
     * Database Column Remarks:
     *   职业方向id
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column occupation.career_direction
     *
     * @mbg.generated Mon Jul 20 02:59:46 CST 2020
     */
    private Integer careerDirection;

    /**
     * Database Column Remarks:
     *   学习方向
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column occupation.major
     *
     * @mbg.generated Mon Jul 20 02:59:46 CST 2020
     */
    private String major;

    /**
     * Database Column Remarks:
     *   图片地址
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column occupation.imges
     *
     * @mbg.generated Mon Jul 20 02:59:46 CST 2020
     */
    private String imges;

    /**
     * Database Column Remarks:
     *   简介
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column occupation.introduce
     *
     * @mbg.generated Mon Jul 20 02:59:46 CST 2020
     */
    private String introduce;

    /**
     * Database Column Remarks:
     *   学习门槛
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column occupation.threshold
     *
     * @mbg.generated Mon Jul 20 02:59:46 CST 2020
     */
    private Integer threshold;

    /**
     * Database Column Remarks:
     *   学习难度
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column occupation.difficulty
     *
     * @mbg.generated Mon Jul 20 02:59:46 CST 2020
     */
    private Integer difficulty;

    /**
     * Database Column Remarks:
     *   成长周期
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column occupation.growth_cycle
     *
     * @mbg.generated Mon Jul 20 02:59:46 CST 2020
     */
    private String growthCycle;

    /**
     * Database Column Remarks:
     *   市场需求量
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column occupation.scarcity
     *
     * @mbg.generated Mon Jul 20 02:59:46 CST 2020
     */
    private Integer scarcity;

    /**
     * Database Column Remarks:
     *   初始薪资
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column occupation.salary
     *
     * @mbg.generated Mon Jul 20 02:59:46 CST 2020
     */
    private Integer salary;

    /**
     * Database Column Remarks:
     *   薪资增长系数
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column occupation.coefficient
     *
     * @mbg.generated Mon Jul 20 02:59:46 CST 2020
     */
    private Float coefficient;

    /**
     * Database Column Remarks:
     *   在学人数
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column occupation.number_of_student
     *
     * @mbg.generated Mon Jul 20 02:59:46 CST 2020
     */
    private Integer numberOfStudent;

    /**
     * Database Column Remarks:
     *   提示信息
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column occupation.prompt
     *
     * @mbg.generated Mon Jul 20 02:59:46 CST 2020
     */
    private String prompt;

    /**
     * Database Column Remarks:
     *   更新时间
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column occupation.updateat
     *
     * @mbg.generated Mon Jul 20 02:59:46 CST 2020
     */
    private Date updateat;

    /**
     * Database Column Remarks:
     *   创建时间
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column occupation.createat
     *
     * @mbg.generated Mon Jul 20 02:59:46 CST 2020
     */
    private Date createat;
}