package cn.mogeek.rmi.ptteng.mapper;

import cn.mogeek.rmi.ptteng.model.Direction;
import cn.mogeek.rmi.ptteng.model.DirectionExample;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface DirectionMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table direction
     *
     * @mbg.generated Mon Jul 20 02:59:46 CST 2020
     */
    long countByExample(DirectionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table direction
     *
     * @mbg.generated Mon Jul 20 02:59:46 CST 2020
     */
    int deleteByExample(DirectionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table direction
     *
     * @mbg.generated Mon Jul 20 02:59:46 CST 2020
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table direction
     *
     * @mbg.generated Mon Jul 20 02:59:46 CST 2020
     */
    int insert(Direction record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table direction
     *
     * @mbg.generated Mon Jul 20 02:59:46 CST 2020
     */
    int insertSelective(Direction record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table direction
     *
     * @mbg.generated Mon Jul 20 02:59:46 CST 2020
     */
    List<Direction> selectByExample(DirectionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table direction
     *
     * @mbg.generated Mon Jul 20 02:59:46 CST 2020
     */
    Direction selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table direction
     *
     * @mbg.generated Mon Jul 20 02:59:46 CST 2020
     */
    int updateByExampleSelective(@Param("record") Direction record, @Param("example") DirectionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table direction
     *
     * @mbg.generated Mon Jul 20 02:59:46 CST 2020
     */
    int updateByExample(@Param("record") Direction record, @Param("example") DirectionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table direction
     *
     * @mbg.generated Mon Jul 20 02:59:46 CST 2020
     */
    int updateByPrimaryKeySelective(Direction record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table direction
     *
     * @mbg.generated Mon Jul 20 02:59:46 CST 2020
     */
    int updateByPrimaryKey(Direction record);
}