package cn.mogeek.rmi.ptteng.mapper;

import cn.mogeek.rmi.ptteng.model.LoginUser;
import cn.mogeek.rmi.ptteng.model.LoginUserExample;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface LoginUserMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table login_user
     *
     * @mbg.generated Mon Jul 20 02:59:46 CST 2020
     */
    long countByExample(LoginUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table login_user
     *
     * @mbg.generated Mon Jul 20 02:59:46 CST 2020
     */
    int deleteByExample(LoginUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table login_user
     *
     * @mbg.generated Mon Jul 20 02:59:46 CST 2020
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table login_user
     *
     * @mbg.generated Mon Jul 20 02:59:46 CST 2020
     */
    int insert(LoginUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table login_user
     *
     * @mbg.generated Mon Jul 20 02:59:46 CST 2020
     */
    int insertSelective(LoginUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table login_user
     *
     * @mbg.generated Mon Jul 20 02:59:46 CST 2020
     */
    List<LoginUser> selectByExample(LoginUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table login_user
     *
     * @mbg.generated Mon Jul 20 02:59:46 CST 2020
     */
    LoginUser selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table login_user
     *
     * @mbg.generated Mon Jul 20 02:59:46 CST 2020
     */
    int updateByExampleSelective(@Param("record") LoginUser record, @Param("example") LoginUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table login_user
     *
     * @mbg.generated Mon Jul 20 02:59:46 CST 2020
     */
    int updateByExample(@Param("record") LoginUser record, @Param("example") LoginUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table login_user
     *
     * @mbg.generated Mon Jul 20 02:59:46 CST 2020
     */
    int updateByPrimaryKeySelective(LoginUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table login_user
     *
     * @mbg.generated Mon Jul 20 02:59:46 CST 2020
     */
    int updateByPrimaryKey(LoginUser record);

    List<LoginUser> selectByKey(String key);
}