package cn.mogeek.rmi.ptteng.mapper;

import cn.mogeek.rmi.ptteng.model.Occupation;
import cn.mogeek.rmi.ptteng.model.OccupationExample;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface OccupationMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table occupation
     *
     * @mbg.generated Mon Jul 20 02:59:46 CST 2020
     */
    long countByExample(OccupationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table occupation
     *
     * @mbg.generated Mon Jul 20 02:59:46 CST 2020
     */
    int deleteByExample(OccupationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table occupation
     *
     * @mbg.generated Mon Jul 20 02:59:46 CST 2020
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table occupation
     *
     * @mbg.generated Mon Jul 20 02:59:46 CST 2020
     */
    int insert(Occupation record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table occupation
     *
     * @mbg.generated Mon Jul 20 02:59:46 CST 2020
     */
    int insertSelective(Occupation record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table occupation
     *
     * @mbg.generated Mon Jul 20 02:59:46 CST 2020
     */
    List<Occupation> selectByExample(OccupationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table occupation
     *
     * @mbg.generated Mon Jul 20 02:59:46 CST 2020
     */
    Occupation selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table occupation
     *
     * @mbg.generated Mon Jul 20 02:59:46 CST 2020
     */
    int updateByExampleSelective(@Param("record") Occupation record, @Param("example") OccupationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table occupation
     *
     * @mbg.generated Mon Jul 20 02:59:46 CST 2020
     */
    int updateByExample(@Param("record") Occupation record, @Param("example") OccupationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table occupation
     *
     * @mbg.generated Mon Jul 20 02:59:46 CST 2020
     */
    int updateByPrimaryKeySelective(Occupation record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table occupation
     *
     * @mbg.generated Mon Jul 20 02:59:46 CST 2020
     */
    int updateByPrimaryKey(Occupation record);
}